"""hide spam stations batch 1

Revision ID: 0014
Revises: 0013
Create Date: 2026-05-19

Hides 41 stations identified as editorial spam during the techno-pilot
review. Source list was generated by `export-spam-candidates` (commit
9cb1f34) into CSVs which were reviewed manually; the resulting "hide"
decisions are baked into SLUGS_TO_HIDE below.

Split: 13 from the spam_score >= 7 auto-hide bucket, 28 from the review
zone where the operator chose hide on editorial grounds. None of the
selected slugs are stations we would have curated.

Rollback: downgrade() flips the same 41 slugs back to hidden=false.
Manual hides applied to OTHER stations between upgrade and downgrade
are NOT touched.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0014"
down_revision: str | Sequence[str] | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


SLUGS_TO_HIDE: list[str] = [
    # --- Hide automáticos del rubric (spam_score >= 7) ---
    "top-100-dj-charts-dj-remix-charts-radio-tiktok-charts-electronic-music-edm-house-deep-house-dance-music-techno-hypertechno-top40-latin-charts-reggaeton-urban-hiphop-club-party-radio-live-dj-sets",
    "top-100-club-charts-dance-dj-mix-radio-24-hours-non-stop-music-tiktok-hits-ibiza-house-sunset-lounge-melodic-music-edm-deep-house-dance-music-techno-hypertechno-rave-charts-top-40-charts-latin-reggaeton-music-moombahton-urban-hits-hiphop-party-clubbing-radio-trending-chartmusic-r-b-urban-mixtape-live-dj-set",
    "charts-3-einfach-dein-lieblingsradio-3-best-of-remixes-club-dance-handsup-mashup-remix-dj-deejay-live-tanzmusik-groove-edm-hard-rave-deep-house-chillout-top-100-top-40-remix-radio-mix-lounge-sunset-afro-house-hardstyle-edm-black-rnb-hip-hop-mix-deep-slow-sleep-german-deejay-radio-mixed-dj-set-festival-mainstream-de-us-en-radio",
    "aktuelle-hits-24h-non-stop-music-dance-dj-mix-radio-tiktok-hits-ibiza-house-sunset-lounge-melodic-music-edm-deep-house-dance-music-techno-hypertechno-rave-charts-top-40-charts-latin-reggaeton-music-moombahton-urban-hits-hiphop-party-clubbing-radio-trending-chartmusic-r-b-urban-mixtape-live-dj-set",
    "neuerscheinungen-radio-charts-dj-charts-club-charts-top-100-top-40-club-pop-hip-hop-dance-edm-house-techno-r-b-trap-reggaeton-afrobeat-indie-pop-tropical-house-future-bass-electro-swing-synthwave-deep-house-progressive-house-vocal-house-dj-sets-remix-mashup-dancefloor-festival-hits-club-hits-nightlife-underground",
    "top-100-partybreakz-dj-mixe-partyremixe-remix-radio-remix-charts-dj-remix-mashup-remix-hits-deejay-remix-radio-partymix-dance-music-techno-hypertechno-top40-latin-charts-reggaeton-urban-hiphop-club-party-radio-live-dj-sets",
    "club-charts-deejay-remix-radio-non-stop-music-ibiza-house-sunset-lounge-melodic-music-edm-deep-house-dance-music-techno-hypertechno-rave-charts-top-40-charts-latin-reggaeton-music-moombahton-urban-hits-hiphop-party-clubbing-radio-trending-charts-rnb-90s-90er-eurodance-urban-dj-mixtapes",
    "partyhits-dein-musikmix-aus-ballermann-apres-ski-wiesn-karneval-silvesterparty-top-100-party-malle-nonstop-dj-live-abriss-feier-bass-feiermusik-partymusik-apres-ski-party-fussball-hits",
    "dj-club-charts-club-classics-festival-hits-remixes-single-charts-mashups-dj-sets-club-edits-dancefloor-underground-nightlife-party-anthems-ibiza-miami-clubbing-festival-remix-mashup-dj-edm-rave-dance-urban-latin-beachclub-lounge",
    "mainstage-charts-your-festival-radio-edm-techno-dj-mixtapes-rave-latin-reggaeton-moombahton-rnb-dj-charts-hiphop-electro-deep-house-dance-lounge-chillout-summer-ibiza-house-wedding-bach-soulful-beach-club-germany-dj-radio-party-breakz-pool-pop-urban-hot-new-music",
    "top-40-deejay-charts-club-charts-nonstop-dance-dj-mix-radio-24-hours-non-stop-music-tiktok-hits-ibiza-house-sunset-lounge-melodic-music-edm-deep-house-dance-music-techno-techhouse-hypertechno-rave-charts-top-40-charts-latin-reggaeton-music-moombahton-urban-hits-hiphop-party-clubbing-radio-trending-chartmusic-r-b-urban-mixtape-live-dj-set",
    "top-100-dj-charts-remix-deejay-radio-club-radio-house-edm-techhouse-techno-dance-top100-top40-rnb-blackmusic-hiphop-urban-reggeaton-mixtape-radio-rave-music-live-deejay-radio-live-events",
    "top-100-charts-dj-mixes-pop-rock-dance-house-techno-trance-electro-hip-hop-rap-rnb-reggaeton-latin-jazz-blues-soul-funk-metal-indie-alternative-chillout-lounge-ambient-classical-acoustic-party-hits-charts-oldies-80s-90s-edm-club-deep-house-tropical-mood-love-songs-workout-relax",
    # --- Hide desde zona review (criterio editorial) ---
    "deejay-remixe-your-radio-for-finest-house-edm-electro-dance-mashup-hypertechno-techno-bootleg-charts-top40-chillout-lounge-hiphop-urban-latin-party-dj-remixes",
    "remix-partybreaks-your-house-edm-hiphop-rnb-techno-techhouse-top-40-charts-latin-dj-mixtape-radio",
    "top-100-club-charts-dj-top-100-up-to-date-dj-charts-clubbing-hits-deep-house-lounge-dance-techno-rave-edm-house-techhouse-remix-trance-hardstyle-minimal-ibiza-chillout-lounge-urban-hip-hop-rnb-summer-ibiza-house-hardstyle-hardcore-remix-mixtape-festival-radio",
    "top-100-dj-charts-remix-radio-tiktok-promo-charts-electronic-music-edm-house-deep-house-dance-music-techno-hypertechno-top40-latin-charts-reggaeton-urban-moombahton-reggaeton-hiphop-funk-club-party-radio-summer-tunes-2024-2025",
    "top-100-dj-charts-remix-radio-tiktok-promo-charts-electronic-music-edm-house-deep-house-dance-music-techno-hypertechno-top40-latin-charts-reggaeton-urban-moombahton-reggaeton-hiphop-funk-club-party-radio-summer-tunes-2024-2025-2",
    "top-100-charts-pop-rock-dance-house-techno-trance-electro-hip-hop-rap-rnb-reggaeton-latin-jazz-blues-soul-funk-metal-punk-indie-alternative-chillout-lounge-ambient-classical-acoustic-singer-songwriter-party-top-40-hits-charts-oldies-80s-90s-2000s-2010s-edm-club-deep-house-tropical-mood-love-songs-workout-relax-study-driving-festival-summer",
    "club-radio-dein-dj-home-dj-remix-charts-electronic-music-edm-house-deep-house-techno-melodic-house-techno-top40-latin-reggaeton-urban-hiphop-club-party-radio",
    "100-handsup-3-non-stop-140-bpm",
    "mainstream-mornings-party-nights-morning-day-mainstream-top-40-charts-evening-night-party-house-techno-dj-mixes-live-djs",
    "club-charts-top-100-club-charts-dj-charts-clubbing-hits-dance-techno-rave-edm-house-techhouse-remix-trance-hardstyle-minimal-ibiza-chillout-urban-hip-hop-rnb-latin-radio",
    "top-200-dj-charts-just-music-dj-remix-charts-radio-tiktok-charts-electronic-music-edm-house-deep-house-dance-music-techno-hypertechno-top40-latin-charts-reggaeton-urban-hiphop-club-party-radio-live-dj-sets-festival-melodic-house-melodic-techno-best-100-lounge-mixed-radio-station-partyhits-schlager-remix-top-50",
    "club-charts-top-100-immer-aktuell-dj-charts-house-edm-deep-house-tech-house-techno-melodic-techno-edm-electronic-dance-music-club-dj-dj-mix-remix-festival-festival-radio-ibiza-ibiza-house-summer-house-beach-club-chillout-lounge-rave-party-music-nightlife-urban-hip-hop-rnb-afro-house-latin-house-trance-hardstyle-hardcore",
    "club-charts-top-100-immer-aktuell-dj-charts-house-edm-deep-house-tech-house-techno-melodic-techno-edm-electronic-dance-music-club-dj-dj-mix-remix-festival-festival-radio-ibiza-ibiza-house-summer-house-beach-club-chillout-lounge-rave-party-music-nightlife-urban-hip-hop-rnb-afro-house-latin-house-trance-hardstyle-hardcore-2",
    "charthits-charthits-fm-house-dance-electro-techno-charts-top40-pop-edm-afro-house-deep-house-techhouse-festival-top-charts-hits-dj-live-set-remix-radio-charts",
    "afro-house-afro-tech-deep-house-organic-house-tribal-house-melodic-house-tropical-house-ethnic-house-latin-house-percussion-house-beach-vibes-summer-vibes-sunset-grooves-ibiza-vibes-warm-up-grooves",
    "edm-festival-festival-edm-big-room-mainstage-electro-house-progressive-house-hard-edm-drops-anthems-party-energy-club-rave-future-edm-bass-peak-time",
    "nicht-einschalten-nichts-ausser-house-edm-hiphop-rnb-techno-techhouse-top-40-charts-latin-afro-sunset-beach-und-aktuelle-hits-dj-mixtape-radio",
    "1-nicht-einschalten-nichts-ausser-house-edm-hiphop-rnb-techno-techhouse-top-40-charts-latin-afro-sunset-beach-dj-mixtape-radio",
    "house-vs-hip-hop-rap-deutschrap-r-b-trap-techno-house-edm-deep-house-hardstyle-trance-drum-bass-lo-fi-chillout-festival-club-party-afterhour-beats-underground-hype-techno-techhouse-top-40-charts-dj-mixtape-radio",
    "edm-100-play-music-2012",
    "melodic-house-techno-technolovers-fm-chillout-beach-festival-sundowner-relax-ibiza-sea-ocean-music-beachclub-cocktailbar-2024-2025-2026-future-rave-126-128-124-beats-per-minute-bpm",
    "deejay-radio-germany",
    "0nline-deejay-radio",
    "deejay-mixes",
    "breakz-fm-charts-remixe",
    "edm-festival-online-radio",
    "edm-festival-online-radio-2",
    "original-edm-festival",
]


def upgrade() -> None:
    result = op.get_bind().execute(
        sa.text(
            "UPDATE stations SET hidden = true "
            "WHERE slug = ANY(:slugs) AND hidden = false",
        ),
        {"slugs": SLUGS_TO_HIDE},
    )
    expected = len(SLUGS_TO_HIDE)
    actual = result.rowcount
    if actual != expected:
        # Soft signal: legitimate reasons for differing are slugs already
        # hidden (e.g. by the PR-1 sync mirror logic between PR 1 merge
        # and this PR landing) or stations dropped upstream. Surface the
        # delta so the operator can decide whether to investigate.
        print(  # noqa: T201
            f"[migration 0014] expected to flip {expected} rows, "
            f"flipped {actual}. OK if some were already hidden or no "
            f"longer exist; investigate if the delta is large.",
        )


def downgrade() -> None:
    op.get_bind().execute(
        sa.text(
            "UPDATE stations SET hidden = false WHERE slug = ANY(:slugs)",
        ),
        {"slugs": SLUGS_TO_HIDE},
    )
